version: "3.8"

services:
  nautilus:
    hostname: nautilus
    image: nautilus
    build: .
    volumes:
      - $HOME/.kube/:/home/nautilus/.kube/
    stdin_open: true
    tty: true
    #command: /bin/bash
    command: /bin/fish
